

IGNORE = {
    'ability', 'advantage', 'agreement', 'agreements', 'alternatives', 'application', 'applications', 'apps', 'aptitude', 'attention', 
    'bachelor', 'building', 
    'challenge', 'challenges', 'clean', 'client', 'code', 'coding', 'collaborate', 'colleagues', 'communication', 'communities', 'company', 
    'compliance', 'components', 'conduct', 'considerations', 'constructive', 'contribute', 'cooperate', 'create', 'culture', 
    'custom', 'customers', 'cutting-edge', 
    'deliver', 'delivery', 'design', 'designers', 'developer', 'development', 'documentation', 'documents', 'drive', 
    'e.g', 'efficiency', 'efficient', 'end', 'end-to-end', 'engineer', 'engineering', 'engineers', 'enhance', 'enhancement', 'enhancements', 
    'environment', 'environments', 'evaluate', 'evaluations', 'exceptional', 'experience', 'experiences', 'expertise', 
    'familiarity', 'fault', 'features', 'feedback', 'field', 'frameworks', 'functionality', 
    'gathering', 'guide', 
    'high-quality', 
    'ideal', 'implement', 'improvement', 'improvements', 'infrastructure', 'inputs', 'insights', 'integration', 'interface', 'issues', 
    'job', 'jpy', 
    'knowledge', 
    'language', 'languages', 'leadership', 'level', 'lifecycle', 'location', 'love', 
    'maintain', 'maintainability', 'manage', 'management', 'manner', 'markup', 'master', 'members', 'middleware', 'mind', 
    'networker', 
    'offer', 'operating', 'optimal', 'optimise', 'optimize', 'organizational', 
    'packages', 'page', 'part', 'party', 'past', 'patterns', 'pay', 'performance', 'performant', 'platform', 'platforms', 'plus', 'portfolio', 
    'position', 'possess', 'practice', 'practices', 'preferences', 'product', 'production', 'products', 'proficiency', 'proficient', 'programing', 
    'programming', 'project', 'projects', 'provide', 
    'quality', 
    'range', 'readability', 'region', 'relationship', 'repositories', 'requests', 'requirement', 'reviews', 'role', 'runs', 
    'salary', 'scratch', 'secure', 'server', 'service', 'site', 'skills', 'soap', 'software', 'solutions', 'specialities', 
    'specialization', 'speed', 'stakeholders', 'standard', 'standards', 'support', 'system', 'systems', 
    'team', 'teams', 'tech', 'technologies', 'technology', 'test', 'testability', 'tickets', 'tolerant', 'tools', 'translation', 'troubleshoot', 
    'understanding', 'university', 'updates', 'usability', 'user', 'verbal', 'version', 'website', 'winning', 'work', 'year', 'years',
}